version: "3.7"

services:
  mongo:
    image: "mvertes/alpine-mongo"
    hostname: "mongo"
    restart: always
    volumes:
      - data-volume:/data/db/
    ports:
      - "27017:27017"
    networks:
      - web_network

  redis:
    image: "redis:4.0-alpine"
    hostname: "redis"
    restart: always
    ports:
      - "6380:6379"
    networks:
      - web_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/code
    ports:
      - "9005:9005"
    links:
      - redis
      - mongo
    networks:
      - web_network

networks:
  web_network:
    name: web_network

volumes:
  data-volume: